# Discord Faucet configuration
verbose = "yes"
core_team_role_id = 957288205391118337

[envs]
    [envs.local]
    node_rpc = "http://localhost:36657"
    node_executable = "dymd"
    node_denom = "udym"
    node_chain_id = "dymension_100-1"
    network_name = "dymension"
    faucet_address = "dym1ctqdmjt7hntk2lxskgkphx73frt5h4f44ehjhx"
    address_prefix = "dym1"
    amount_to_send = "1000000"
    amount_to_send_evm = "1000000000000000000"
    daily_cap = "100000000"
    daily_cap_evm = "100000000000000000000"
    tx_fees = "10"
    block_explorer_tx=""
    token_requests_cap = 2
    ibc_token_requests_cap = 1
    ibc_enabled = true
    channels_to_listen = ""
    request_timeout = "604800"

    [envs.devnet]
    node_rpc = "https://dymension-devnet.rpc.silknodes.io:443"
    node_executable = "dymd"
    node_denom = "udym"
    node_chain_id = "devnet_304-1"
    network_name = "dymension"
    faucet_address = "dym1lm90mcfyrcu8xngghxx4qq68q4pnppwtxeltcy"
    address_prefix = "dym1"
    amount_to_send = "1000000"
    amount_to_send_evm = "1000000000000000000"
    daily_cap = "100000000"
    daily_cap_evm = "100000000000000000000"
    tx_fees = "10"
    block_explorer_tx=""
    token_requests_cap = 2
    ibc_token_requests_cap = 1
    ibc_enabled = true
    channels_to_listen = "bere"
    request_timeout = "604800"

    [envs.celestia]
    node_rpc = "https://rpc-arabica-9.consensus.celestia-arabica.com:443"
    node_executable = "celestia"
    node_denom = "utia"
    node_chain_id = "arabica-9"
    network_name = "arabica-9"
    faucet_address = "celestia1emd05tmxqy5z9mlccvudrmj8hnmds49t2le2r2"
    address_prefix = "celestia1"
    amount_to_send = "100000"
    daily_cap = "10000000"
    tx_fees = "10"
    block_explorer_tx=""
    token_requests_cap = 1
    ibc_enabled = false
    channels_to_listen = ""
    request_timeout = "604800"

