# Cosmos Discord Faucet configuration

verbose        = "yes"

[dymension]
prefix         = "dym"
denomination   = "udym"
executable     = "dymd"

[testnets]
    [testnets.c-35]
    node_url = "http://localhost:26657"
    chain_id = "hub"
    faucet_address = "dym1teld7n32u5ll3kptw5jz5zrwy6jxs8702huxtu"
    block_explorer_tx = "https://explorer.theta-testnet.polypore.xyz/transactions/"
    daily_cap = "1000"
    amount_to_send = "100"
    tx_fees = "10"

    [testnets.devnet]
    node_url = "http://localhost:26657"
    chain_id = "hub"
    faucet_address = "dym1teld7n32u5ll3kptw5jz5zrwy6jxs8702huxtu"
    block_explorer_tx = ""
    daily_cap = "1000"
    amount_to_send = "20"
    tx_fees = "10"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "bere"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"