# Cosmos Discord Faucet configuration

verbose        = "yes"

[testnets]
    [testnets.c-35]
    node_url = "http://localhost:36657"
    chain_id = "local-testnet"
    faucet_address = "dym1gcx0e7vhdqjsjj3jnpy6twlna8nfhqrzf76zwa"
    executable = "dymd"
    address_prefix = "dym"
    denom = "udym"
    block_explorer_tx = ""
    daily_cap = "1000"
    amount_to_send = "100"
    tx_fees = "10"

    [testnets.rollapp-a]
    node_url = "http://localhost:26667"
    chain_id = "rollapp"
    faucet_address = "rol1duet48wzj44evxe9pv627u6jpcf2mvzucjke0x"
    executable = "rollappd"
    address_prefix = "rol"
    denom = "urap"
    block_explorer_tx = ""
    daily_cap = "1000"
    amount_to_send = "20"
    tx_fees = "10"

[discord]
# comma separated list of channels
channels_to_listen = "bere"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"